package monsterRun.common.model.enums;

public enum MessageID {

	GAME_JOIN_REQUEST, GAME_STARTED, GAME_FINISHED,

	CLIENT_CONNNECTED, CLIENT_MOVED, MONSTER_MOVED, CLIENT_MOVE_REQUEST,

	SERVER_FULL, GAME_DETAILS, INVALID_INPUT,

	SPECIFY_GAME_DETAILS, SPECIFY_PLAYERS_DONE, SPECIFY_BOARD, SPECIFY_BOARD_DONE,

	CLIENT_DETAILS, PLAYER_DEAD, PLAYER_NUM_LIVES_LEFT,

	START_POS_REQUEST, START_POS_RESPONSE
}
